name: $(Build.SourceVersion)
jobs:
- job: Linux
  timeoutInMinutes: 0
  pool:
    vmImage: 'Ubuntu 16.04'

  variables:
    STAGING_DIRECTORY: /home/vsts/STAGING
    STAGING_DIRECTORY_UNIX: /home/vsts/STAGING

  steps:
  - template: .ci/use-node.yml
  - template: .ci/docusaurus-build.yml
  - template: .ci/docusaurus-test.yml
  - template: .ci/docusaurus-publish.yml
